/*
 * This source file was generated by the Gradle 'init' task
 */
package com.outpost;

public class App {
    public static void main(String[] args) {
        Game game = new Game();
        game.start();
    }
}
